version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3900:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "start"]